language: android
 env:
  matrix:
    - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a
before_install:
 - chmod +x gradlew
 - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
 - emulator -avd test -no-skin -no-audio -no-window &
 - adb wait-for-device
 - while [[ `adb shell pm path android` == 'Error'* ]]; do sleep 2; done
 - adb shell input keyevent 82 &

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    # - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-28
    - sys-img-armeabi-v7a-android-28
